openapi: 3.0.3
info:
  version: 1.0.0
  title: Rapurc API-spec

security:
  - bearerAuth: []

paths:
  /v1/system/ping:
    get:
      operationId: ping
      summary: Replies with pong
      description: Replies ping with pong
      tags:
        - System
      responses:
        "200":
          description: Pong
          content:
            text/plain:
              schema:
                type: string

  /v1/surveys:
    get:
      operationId: listSurveys
      summary: List surveys.
      description: Lists surveys.
      tags:
        - Surveys
      parameters:
        - name: firstResult
          in: query
          description: First result. Defaults to 0
          required: false
          schema:
            type: integer
        - name: maxResults
          in: query
          description: Max results. Defaults to 10
          required: false
          schema:
            type: integer
        - name: address
          in: query
          description: Filter by address
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: Filter by survey status
          required: false
          schema:
            $ref: "#/components/schemas/SurveyStatus"
      responses:
        "200":
          description: List of surveys
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Survey"
          headers:
            X-Total-Count:
              schema:
                type: integer
                format: int64
              description: Total count of surveys with given filters.
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: createSurvey
      summary: Create a survey.
      description: Creates a new survey.
      tags:
        - Surveys
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Survey"
        description: Payload
        required: true
      responses:
        "200":
          description: Created Survey
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Survey"
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  "/v1/surveys/{surveyId}":
    get:
      operationId: findSurvey
      summary: Find a survey.
      description: Finds a survey by id.
      tags:
        - Surveys
      parameters:
        - name: surveyId
          required: true
          in: path
          description: survey id
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Survey
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Survey"
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      operationId: updateSurvey
      summary: Update a survey.
      description: Updates a survey
      tags:
        - Surveys
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Survey"
        description: Payload
        required: true
      parameters:
        - name: surveyId
          required: true
          in: path
          description: survey id
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Updated Survey
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Survey"
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      operationId: deleteSurvey
      summary: Delete a survey.
      description: Deletes a survey.
      tags:
        - Surveys
      parameters:
        - name: surveyId
          required: true
          in: path
          description: survey id
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Success
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      description: Error object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    Survey:
      type: object
      description: Survey object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the survey
          readOnly: true
        status:
          $ref: "#/components/schemas/SurveyStatus"
        creatorId:
          type: string
          format: uuid
          description: ID of creator
          readOnly: true
        lastModifierId:
          type: string
          format: uuid
          description: Id of last modifier
          readOnly: true
        createdAt:
          type: string
          format: date-time
          description: Created date
          readOnly: true
        modifiedAt:
          type: string
          format: date-time
          description: Date modified
          readOnly: true

    SurveyStatus:
      type: object
      description: Survey status enum
      enum:
        - DRAFT
        - DONE